---
- name: Start Arch installs
  ansible.builtin.debug:
    msg: "Running Arch installs"
- name: Packman installs
  become: true
  community.general.pacman:
    name:
      - "fd"
      - "base-devel"
      - "git"
- name: Clone Yay
  ansible.builtin.git:
    repo: "https://aur.archlinux.org/yay.git"
    dest: ~/.repos/yay
- name: Package Yay
  makepkg:
    name: yay
    state: present
    build_dir: "~/.repos/yay"
