---

- name: Check if LunarVim is installed.
  stat:
    path: ~/.local/bin/lvim
  register: lvim_stat
  become: false
    

- name: Download Installer
  get_url:
    url: https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh
    dest: "{{ temp_dir.path }}"
  when: lvim_stat.stat.exists == false

- name: Set Permissions for installer.
  become: true
  file:
    path: "{{ temp_dir.path }}/install.sh"
    mode: 0777
  when: lvim_stat.stat.exists == false

- name: Run installer
  become: false
  shell: "./install.sh"
  environment:
    LV_BRANCH: "release-1.3/neovim-0.9"

  args:
    chdir: "{{ temp_dir.path }}"
  when: lvim_stat.stat.exists == false

  
