---

- name: Download Installer
  get_url:
    url: https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh
    dest: "{{ temp_dir.path }}"

- name: Set Permissions for installer.
  shell: "chmod 777 .install.sh"
  args:
    chdir: "{{ temp_dir.path }}"

- name: Run installer
  shell: "./install.sh"
  args:
    chdir: "{{ temp_dir.path }}"

  
