# load-configs.yml

---
- name: Check if .configs exists
  stat:
    path: ~/.config
  register: conf_stat
  become: false

- name: Remove .configs
  file:
    path: ~/.config
    state: absent
  when: conf_stat.stat.exists == false
    
- name: Link Configs 
  file:
    src: ~/.dotfiles/.config
    dest: ~/.config
    state: link

