# Main Playbook

---
- name: Main Playbook
  hosts: localhost
  become: false 
  gather_facts: yes
  vars:
    powerlevel10k_path: "~/.powerlevel10k"
  tasks:
        
    - name: Apt installs
      become: true
      include: apt-installs.yml

    - name: Set git User Email
      git_config:
        name: "user.email"
        value: "thechad802@gmail.com"
        scope: "global"

    - name: Set git User Name
      git_config:
        name: "user.name"
        value: "Chad Provencher"
        scope: "global"

    - name: Load Configs
      include: load-configs.yml

    - name: Create temp directory.
      tempfile:
        state: directory
      register: temp_dir

    - name: Create User Bin Dir
      file:
        path: ~/.local/bin
        state: directory
      register: user_bin_folder

    - name: Create User Build Dir
      file:
        path: ~/.local/build
        state: directory
      register: user_build_folder

    - name: Install Fonts
      become: false
      include: fonts-install.yml

    - name: Install ZSH 
      become: false
      include: install-zsh.yml

    - name: Build TMUX
      include: build-tmux.yml

    - name: Setup TMUX
      include: configure-tmux.yml

    - name: Build Neovim
      become: False
      include: build-neovim.yml

  post_tasks:
    - name: Delete Temp Dir
      become: true
      file: 
        path: "{{ temp_dir.path }}"
        state: absent
      when: temp_dir.path is defined and temp_dir.path | length > 0


