---
- name: Set Git Config Settings
  git_config:
    scope: global
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - {name: "user.name", value: "Chad Provencher"}
    - {name: "user.email", value: "thechad802@gmail.com"}
    - {name: "credential.helper", value: "store --file ~/.password-store/git-credentials.pass" }
