---
- name: Register SSH Key with GitHub
  community.general.github_key:
    name: "{{ ansible_hostname }}-{{ ansible_distribution }}"
    token: "{{ github_token }}"
    pubkey: "{{ public_key }}"
    state: present
