# load-configs.yml

---
- name: Check if .configs exists
  stat:
    path: ~/.config
  register: conf_stat
  become: false

- name: Remove configs
  file:
    dest: "~/.config/{{ item }}"
    state: "absent"
  with_items:
    - "nvim"
    - "nnn"
    - "neofetch"
    - "tmux"
    - "zsh"

- name: Link Configs
  file:
    src: "~/.dotfiles/.config/{{ item }}"
    dest: "~/.config/{{ item }}"
    state: "link"
  with_items:
    - "nnn"
    - "neofetch"
    - "tmux"
    - "zsh"

- name: Setup ZSH config.
  block:
    - name: Check if .zshrc exists
      stat:
        path: ~/.zshrc
      register: zsh_conf_stat
    - name: Create Symbolic link for zsh conf
      file:
        src: ~/.dotfiles/.config/zsh/.zshrc
        dest: ~/.zshrc
        state: link
      when: zsh_conf_stat.stat.exists == false

    - name: Check if .shrc exists
      stat:
        path: ~/.p10k.zsh
      register: p10k_conf_stat
    - name: Create Symbolic link for zsh conf
      file:
        src: ~/.dotfiles/.config/zsh/.p10k.zsh
        dest: ~/.p10k.zsh
        state: link
      when: p10k_conf_stat.stat.exists == false
