# nnn-install.yml
---
- name: Check NeoVim installed
  become: false
  command: which nnn
  register: nnn_check
  ignore_errors: true

- name: Check NNN Cloned
  stat:
    path: "/tmp/nnn"
  register: nnn_cloned_folder

- name: Clone NNN to {{ user_build_folder.path }}/nnn
  git:
    repo: "https://github.com/jarun/nnn.git"
    dest: "/tmp/nnn"
  when: nnn_cloned_folder.stat.exists == false

- name: Build NNN
  become: true
  shell: "make O_NERD=1"
  args:
    chdir: "/tmp/nnn"
  when: nnn_check.rc != 0

- name: Install NNN
  become: true
  shell: "make install"
  args:
    chdir: "/tmp/nnn"
    creates: "/usr/local/bin/nnn"
