# Build NeoVim
---
- name: Check NeoVim installed
  become: false
  command: which nvim
  register: nvim_check
  ignore_errors: true

- name: Check NeoVim Is Cloned
  stat:
    path: "{{ repos }}/neovim"
  register: nvim_repo_stat

- name: Clone Neo Vim
  git:
    repo: https://github.com/neovim/neovim.git
    version: stable
    dest: "{{ repos }}/neovim"
  when: (nvim_check.rc != 0) and (nvim_repo_stat.stat.exists == false)

- name: Build NeoVim
  shell: "make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_INSTALL_PREFIX={{ local }}"
  become: false
  args:
    chdir: "{{ repos }}/neovim"
  when: nvim_check.rc != 0

- name: Install NeoVim
  become: false
  shell: "make install"
  args:
    chdir: "{{ repos }}/neovim"
  when: nvim_check.rc != 0
