# fonts-install.yml
---
- name: Create User Share Folder
  file:
    path: ~/.local/share/fonts
    state: directory
  register: user_font_folder
- name: Get Hack Nerd Font
  get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Hack/Regular/HackNerdFont-Regular.ttf"
    dest: "{{ user_font_folder.path }}/HackNerdFont-Regular.ttf"
- name: Update Fonts Cache
  shell: "fc-cache -f -v"
