
---
- name: Check Tmux installed
  become: false
  command: which tmux
  register: tmux_check
  ignore_errors: yes

- name: Clone Tmux
  git:
    repo: https://github.com/tmux/tmux.git
    version: "3.3a"
    dest: "{{ repos }}/tmux"
  when: tmux_check.rc != 0

- name: Set Permissions for installer.
  become: true
  file:
    path: "{{ repos }}/tmux/autogen.sh"
    mode: 0777
  when: tmux_check.rc != 0

- name: TMUX autogen
  become: true
  shell: "sh ./autogen.sh"
  args:
    chdir: "{{ repos }}/tmux"
  when: tmux_check.rc != 0

- name: "Build TMUX"
  become: true
  shell: "./configure && make"
  args:
    chdir: "{{ repos }}/tmux"
  when: tmux_check.rc != 0

- name: Install TMUX
  become: true
  shell: "make install"
  args:
    chdir: "{{ temp_dir.path }}/tmux"
  when: tmux_check.rc != 0

