# build-zsh.yml

---
- name: Install P10k
  block:
    - name: Download PowerLevel10k
      git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: "{{ repos }}/powerlevel10k"
        depth: 1
    
- name: Setup ZSH completion.
  block:
    - name: Clone zsh-completion
      git:
        repo: https://github.com/marlonrichert/zsh-autocomplete.git
        dest: "{{ repos }}/zsh-autocomplete"
        depth: 1



