---
- name: Set folder facts
  set_fact:
    local: "~/.local"
    bin: "~/.local/bin"
    repos: "~/.local/repos"
    share: "~/.local/share"

- name: Create Local Folders
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ local }}"
    - "{{ bin }}"
    - "{{ repos }}"
    - "{{ share }}"
  register: local_folders
