---
- name: Attempt Repo Update
  block:
    - name: Update apt cache
      become: true
      apt:
        update_cache: true
      when: ansible_os_family == 'Debian'
      ignore_errors: true
  always:
    - name: Install required packages
      become: true
      apt:
        name:
          - net-tools
          - ssh
          - build-essential
          - libarchive-tools
          - wget
          - snap
          - make
          - unzip
          - fontconfig
          - pkg-config
          - libreadline-dev
          - libpthread-stubs0-dev
          - cmake
          - libtool
          - libtool-bin
          - gettext
          - ninja-build
          - curl
          - htop
          - ncdu
          - zsh
          - cargo
          - automake
          - autoconf
          - libevent-dev
          - bison
          - libsecret-tools
          - libncurses5-dev
          - libreadline-dev
          - treeview
          - ripgrep
          - tabbed
          - sxiv
          - mpv
          - file
          - xdotool
          - python3-venv
          - fd-find
          - git-lfs
          - pass
          - pass-extension-tomb
          - wl-clipboard
          - software-properties-common
        state: present

    - name: Install from non-default repos
      block:
        - name: Add Deadsnakes Repo
          become: true
          apt_repository:
            repo: "ppa:deadsnakes/ppa"
            state: present

        - name: Install required packages
          become: true
          apt:
            name:
              - python3.10
              - python3.10-venv
      ignore_errors: true
