# Main Playbook
---
- name: Main Playbook
  hosts: localhost
  become: false 
  gather_facts: yes
  vars_prompt:
    - name: pass_repo
      prompt: 'Enter Pass Repo URL: '
    - name: pass_key_location
      prompt: 'Enter the location of your pass key: '
    - name: pass_key_password
      prompt: 'Enter your pass-store password: '
      private: yes
  vars:
    custom_folder_path: "~/.config/nvim/lua/custom"
  tasks:
    - name: System Installs and Staging
      block:
        - name: Staging
          include: "staging/{{ item }}"
          with_items:
            - "requirements.yml"
            - "folders.yml"
            - "git.yml"

    - name: Custom Builds & Installs
      block:
        - name: Custom Installs
          include: "installs/{{ item.file }}"
          with_items:
            - {file: "zsh.yml"}
            - {file: "node.yml"}
            - {file: "fonts.yml"}
            - {file: "tmux.yml"}
            - {file: "nvim.yml"}
            - {file: "nnn.yml"}
            - {file: "nvchad.yml"}

  post_tasks:
    - name: Load Configs
      include: config/load-configs.yml

    - name: Configure TMUX
      include: config/tmux.yml
