- hosts: localhost
  name: Main Playbook
  gather_facts: true
  vars_files:
    - "vars/github-token.yml"
    - "vars/common.yml"
    - ["vars/{{ ansible_os_family }}.yml", "vars/os_defaults.yml"]
  tasks:
    - name: OS Family Test
      ansible.builtin.debug:
        msg: "{{ ansible_os_family }}"
    - name: Install packages
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      become: true
      with_items:
        - { name: vim, state: latest }
        - { name: neovim, state: latest }
        - { name: wget, state: latest }
        - { name: make, state: latest }
        - { name: unzip, state: latest }
        - { name: fontconfig, state: latest }
        - { name: pkg-config, state: latest }
        - { name: cmake, state: latest }
        - { name: libtool, state: latest }
        - { name: gettext, state: latest }
        - { name: curl, state: latest }
        - { name: htop, state: latest }
        - { name: ncdu, state: latest }
        - { name: zsh, state: latest }
        - { name: cargo, state: latest }
        - { name: automake, state: latest }
        - { name: autoconf, state: latest }
        - { name: bison, state: latest }
        - { name: ripgrep, state: latest }
        - { name: sxiv, state: latest }
        - { name: mpv, state: latest }
        - { name: file, state: latest }
        - { name: xdotool, state: latest }
        - { name: git-lfs, state: latest }
        - { name: pass, state: latest }
        - { name: wl-clipboard, state: latest }
        - { name: software-properties-common, state: latest }

    - name: PPA and Installs
      ansible.builtin.include_tasks:
        file: "distros/{{ ansible_os_family }}/installs.yml"

    - name: Run common
      ansible.builtin.include_tasks:
        file: "common/{{ item }}"
      with_items:
        - "folders.yml"
        - "ssh-keygen.yml"
        - "fonts.yml"
        - "get-keyring.yml"
        - "git.yml"
        - "github.yml"
        - "load-configs.yml"
        - "nnn.yml"
        - "node.yml"
        - "nvchad.yml"
        - "tmux.yml"
        - "zsh.yml"
